export 'ui/login.dart';
export 'ui/home.dart';
export 'ui/qr.dart';
export 'ui/machine.dart';
export 'ui/history.dart';
export 'ui/plans.dart';
export 'ui/repairs.dart';
export 'ui/zaprafka.dart';
export 'ui/admin.dart';
